### ISSUE TITLE
Use binary for length

### ISSUE THREAD

**Issue by tshemsedinov** [bugagashenkj/cryptography#3]
It looks like you want to encode number to string here
https://github.com/bugagashenkj/cryptography/blob/00bec7fd4946ec8f9a18ba22019864f14ed56bcc/lib/file-crypt.js#L23
It is better to use buffers `new Buffer.from([len])`
If you want to pad: `len.toString().padStart(5, '0')`

**Comment by bugagashenkj** [comment]
Used padStart to create length of header.
