### ISSUE TITLE
Optimize condition

### ISSUE THREAD

**Issue by tshemsedinov** [bugagashenkj/cryptography#5]
`if (!(callback && typeof(callback) === 'function'))`
to
`if (!callback || typeof(callback) !== 'function')`
or 
`if (typeof(callback) !== 'function')`
will be ok here

Refs: https://github.com/bugagashenkj/cryptography/blob/00bec7fd4946ec8f9a18ba22019864f14ed56bcc/lib/file-crypt.js#L36

**Comment by bugagashenkj** [comment]
Replaced
if (!(callback && typeof(callback) === 'function')) { 
to
if (typeof(callback) !== 'function')
